@startuml
'https://plantuml.com/sequence-diagram

WebsiteGenerator : + main()
WebsiteGenerator : + createFolder(String ans, String fileType, String folder, String ex43Dir)
WebsiteGenerator : + askQuestion(String string)

@enduml