@startuml
'https://plantuml.com/sequence-diagram
class WordFrequencyFinder
{
{static} ArrayList<String> wordArray
+ main()
+ printOutput(ArrayList<Integer> wordCount)
+ countForEachWord(ArrayList<String> inputWordArray)
+ fileWordsToArray(String s)
}

@enduml