@startuml
'https://plantuml.com/sequence-diagram

WordFinder : + main()
WordFinder : + fileToCharArray(Scanner fileScanner)
WordFinder : + utilizeToUse(char[] inputCharArray, BufferedWriter writer)

@enduml